### ISSUE TITLE
trying to flash on MKS GEN 1.4 - board error 

### ISSUE THREAD

**Issue by shottydan** [MorrisC2010/TH3D-UFW-Ender3-MKS-Gen-1.4#1]
hi!
I'm following yr TH3D guide to flash it on an Ender3 on a MKS GEN 1.4
when I compile, with Arduino board, errors appears (a tenth) telling to change board with sanguino.
what I miss?
I copied all yr TH3DUF_R2, marking original TH3D folder as "old", and tried, with errors...
thanks if you can help me to flash this great fw I used on stock Ender3.

**Comment by MorrisC2010** [comment]
Can you post the log?

**Comment by MorrisC2010** [comment]
Im assuming you fixed whatever the issue was, so ill close this issue
